### ISSUE TITLE
Can we add this to the ooni website?

### ISSUE THREAD

**Issue by hellais** [hermes-diactoros/cripto.cat.grav#1]
Hi, we would like to use your translation in the ooni.torproject.org website.

Can we do that?

We forgot the "Share-Alike" in our LICENSE, so by default we should ask for permissions to do this.

**Comment by hermes-diactoros** [comment]
Absolutely, please go ahead. We will explicitly license most content on our website under CC BY-NC-SA shortly.

**Comment by hellais** [comment]
Thanks!
